/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package session3;

import session2.Estudiante;
import session2.EstudianteModel;

/**
 *
 * @author Docente
 */
public class EstudianteFrame extends java.awt.Frame {

    private EstudianteModel emodel;
    /**
     * Creates new form EstudianteFrame
     */
    public EstudianteFrame() {        
        initComponents();
        emodel = new EstudianteModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFrmEstudiante = new java.awt.Button();
        textArea1 = new java.awt.TextArea();
        btnshow = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        btnFrmEstudiante.setLabel("Formulario Estudiante");
        btnFrmEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrmEstudianteActionPerformed(evt);
            }
        });
        add(btnFrmEstudiante, java.awt.BorderLayout.NORTH);
        add(textArea1, java.awt.BorderLayout.CENTER);

        btnshow.setLabel("Mostrar");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });
        add(btnshow, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(606, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnFrmEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrmEstudianteActionPerformed
        EstudianteDlg edlg = new EstudianteDlg(this,true);
        edlg.setEmodel(emodel);
        edlg.setVisible(true);        
    }//GEN-LAST:event_btnFrmEstudianteActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
        textArea1.setText("");
        textArea1.validate();
        for(Estudiante e : emodel.getAll()){
            textArea1.append(e.toString() + "\n");
        }
    }//GEN-LAST:event_btnshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnFrmEstudiante;
    private java.awt.Button btnshow;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
